name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - master
      - main
  paths:
    include:
      - examples/bastion_vm
    exclude:
      - examples/bastion_vm/README.md
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: bcochofel/azuredevops-pipeline-templates
      ref: refs/heads/main
      endpoint: GitHubConnection

stages:
  - template: terraform/terraform.yml@templates
    parameters:
      environment: sandbox
      varGroups:
        - terraform-configuration
        - terraform-configuration-secrets
      workingDirectory: examples/bastion_vm
      prComments: false
      backendKey: example-bastion.tfstate
